#!/bin/bash
curl -s -X PUT http://localhost:8081/api/admin/movies/1 -H 'Content-Type: application/json' -d '{"id": 1, "title": "AVENGERS: ENDGAME", "genre": "ACTION / SCI-FI", "duration": 181, "synopsis": "The Avengers assemble once more in order to undo Thanos'\'' actions.", "price": 50000.0, "imageUrl": "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg", "status": null, "info": "AVENGERS: ENDGAME (ACTION / SCI-FI) - 181 mins"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/schedules -H 'Content-Type: application/json' -d '{"movie": {"id": 1}, "date": "2026-06-20", "time": "19:00", "hall": "Studio 1"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/schedules -H 'Content-Type: application/json' -d '{"movie": {"id": 2}, "date": "2026-06-20", "time": "19:00", "hall": "Studio 1"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/schedules -H 'Content-Type: application/json' -d '{"movie": {"id": 3}, "date": "2026-06-20", "time": "19:00", "hall": "Studio 1"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/schedules -H 'Content-Type: application/json' -d '{"movie": {"id": 4}, "date": "2026-06-20", "time": "19:00", "hall": "Studio 1"}' > /dev/null
curl -s -X PUT http://localhost:8081/api/admin/movies/5 -H 'Content-Type: application/json' -d '{"id": 5, "title": "LEGO\u00ae Batman\u2122: Legacy of the Dark Knight", "genre": "Children", "duration": 120, "synopsis": "Lego lucu", "price": 200000.0, "imageUrl": "https://image.tmdb.org/t/p/w500/snGwr2gag4Fcgx2zGQxgjtxcprG.jpg", "status": "Coming Soon", "info": "LEGO\u00ae Batman\u2122: Legacy of the Dark Knight (Children) - 120 mins"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/schedules -H 'Content-Type: application/json' -d '{"movie": {"id": 7}, "date": "2026-06-20", "time": "19:00", "hall": "Studio 1"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/schedules -H 'Content-Type: application/json' -d '{"movie": {"id": 8}, "date": "2026-06-20", "time": "19:00", "hall": "Studio 1"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/schedules -H 'Content-Type: application/json' -d '{"movie": {"id": 10}, "date": "2026-06-20", "time": "19:00", "hall": "Studio 1"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/schedules -H 'Content-Type: application/json' -d '{"movie": {"id": 11}, "date": "2026-06-20", "time": "19:00", "hall": "Studio 1"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/schedules -H 'Content-Type: application/json' -d '{"movie": {"id": 12}, "date": "2026-06-20", "time": "19:00", "hall": "Studio 1"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/schedules -H 'Content-Type: application/json' -d '{"movie": {"id": 14}, "date": "2026-06-20", "time": "19:00", "hall": "Studio 1"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/schedules -H 'Content-Type: application/json' -d '{"movie": {"id": 15}, "date": "2026-06-20", "time": "19:00", "hall": "Studio 1"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/schedules -H 'Content-Type: application/json' -d '{"movie": {"id": 17}, "date": "2026-06-20", "time": "19:00", "hall": "Studio 1"}' > /dev/null
curl -s -X PUT http://localhost:8081/api/admin/movies/9 -H 'Content-Type: application/json' -d '{"id": 9, "title": "Interstellar", "genre": "Sci-Fi", "duration": 169, "synopsis": "A team of explorers travel through a wormhole in space in an attempt to ensure humanitys survival.", "price": 50000.0, "imageUrl": "https://image.tmdb.org/t/p/w500/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg", "status": "Now Showing", "info": "Interstellar (Sci-Fi) - 169 mins"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/schedules -H 'Content-Type: application/json' -d '{"movie": {"id": 9}, "date": "2026-06-20", "time": "19:00", "hall": "Studio 1"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/movies -H 'Content-Type: application/json' -d '{"title": "Deadpool & Wolverine", "genre": "Action", "duration": 127, "synopsis": "Wolverine is recovering from his injuries when he crosses paths with the loudmouth, Deadpool.", "price": 50000, "imageUrl": "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg", "status": "Coming Soon"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/movies -H 'Content-Type: application/json' -d '{"title": "Inside Out 2", "genre": "Animation", "duration": 96, "synopsis": "Teenager Riley'\''s mind headquarters is undergoing a sudden demolition.", "price": 40000, "imageUrl": "https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg", "status": "Coming Soon"}' > /dev/null
curl -s -X POST http://localhost:8081/api/admin/movies -H 'Content-Type: application/json' -d '{"title": "Gladiator II", "genre": "Action", "duration": 150, "synopsis": "Years after witnessing the death of the revered hero Maximus.", "price": 60000, "imageUrl": "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg", "status": "Coming Soon"}' > /dev/null
