INSERT INTO `movies` (`duration`, `genre`, `price`, `synopsis`, `title`, `image_url`, `status`) VALUES
(148, 'Sci-Fi / Thriller', 50000, 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea.', 'INCEPTION', 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg', 'Now Showing'),
(169, 'Sci-Fi / Drama', 50000, 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 'INTERSTELLAR', 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg', 'Now Showing'),
(136, 'Action / Sci-Fi', 50000, 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth.', 'THE MATRIX', 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg', 'Now Showing'),
(127, 'Action / Comedy', 50000, 'Deadpool\'s peaceful existence comes crashing down when the Time Variance Authority recruits him to help safeguard the multiverse.', 'DEADPOOL & WOLVERINE', 'https://m.media-amazon.com/images/M/MV5BZTk5YWQyNTktZjc4OS00MzUxLThlNDktZWIxZTg0ZmNjMWEwXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_.jpg', 'Now Showing'),
(166, 'Sci-Fi / Adventure', 50000, 'Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.', 'DUNE: PART TWO', 'https://m.media-amazon.com/images/M/MV5BODdjMjM3NGQtZDA5OC00NGE4LWIyZDQtZjYwOGZlMTM5ZTQ1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg', 'Now Showing'),
(138, 'Thriller / Musical', 45000, 'Sequel to the film "Joker" (2019). Arthur Fleck meets the love of his life.', 'JOKER: FOLIE À DEUX', 'https://m.media-amazon.com/images/M/MV5BZDliZWRmYmItMmVmZC00MDNjLWEwOGMtOTMyODcyZDJjNGI1XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg', 'Coming Soon'),
(150, 'Action / Drama', 45000, 'Follows Lucius, the son of Maximus\' love Lucilla, after Maximus\' death.', 'GLADIATOR II', 'https://m.media-amazon.com/images/M/MV5BMGU5NmQ4NmMtYWIwMS00NTA1LThlNGQtNzJjZjVkMTc2NDYwXkEyXkFqcGc@._V1_.jpg', 'Coming Soon'),
(118, 'Action / Sci-Fi', 45000, 'Sam Wilson, the new Captain America, finds himself in the middle of an international incident.', 'CAPTAIN AMERICA: BRAVE NEW WORLD', 'https://m.media-amazon.com/images/M/MV5BNTg1NWJlMmItMmIzNS00NzgxLWEwOGEtZDFlMmQwMDZhNDU1XkEyXkFqcGc@._V1_.jpg', 'Coming Soon'),
(130, 'Action / Thriller', 45000, 'Ethan Hunt and his IMF team embark on their most dangerous mission yet.', 'MISSION: IMPOSSIBLE 8', 'https://m.media-amazon.com/images/M/MV5BNjRlZmM0ODktY2RjNS00ZDdjLWJhZGYtNDljNWZkMGM5MTg0XkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg', 'Coming Soon'),
(120, 'Animation / Family', 45000, 'Following Riley in her teenage years, encountering new emotions.', 'INSIDE OUT 2', 'https://m.media-amazon.com/images/M/MV5BYzc4MDgxZDItZjMwOS00YWI5LWEwM2EtNWE3ZTIzZjc2ZGE1XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg', 'Coming Soon');

INSERT INTO `advertisements` (`active`, `image_url`, `link_url`, `sort_order`, `title`) VALUES
(1, 'https://cms.cgv.id/uploads/promotions/2301/PR202301131102551486.jpg', 'https://cinema.com/promo/bank-discount', 1, 'Diskon 50% Mandiri'),
(1, 'https://cms.cgv.id/uploads/promotions/2403/PR202403061611139442.jpg', 'https://cinema.com/promo/buy-1-get-1', 2, 'Buy 1 Get 1 Free BCA'),
(1, 'https://cms.cgv.id/uploads/promotions/2402/PR202402011707255132.jpg', 'https://cinema.com/promo/popcorn', 3, 'Combo Popcorn Deals');
